name: Wheels Test

on:
  workflow_dispatch:
    inputs:
      delay_seconds:
        description: "Time to delay"
        required: false
        default: "30"
  push:

jobs: 
  test-wheels:
    
    runs-on: ubuntu-18.04


    steps:

    - name: check an env name
      run: echo "${{ github.ref }}"

    - name: Waiting for wheels
      uses: lewagon/wait-on-check-action@v0.2
      with:
        ref: ${{ github.ref }}
        check-name: wheels # name of the existing check - omit to wait for all checks
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 20 # seconds

    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        # Optional, the status or conclusion of a completed workflow to search for
        # Can be one of a workflow conclusion::
        # "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
        # Or a workflow status:
        # "completed", "in_progress", "queued"
        # Default: "completed,success"
        running-workflow-name: test_wheels
        workflow: wheels.yml
        commit: ${{github.event.pull_request.head.sha}}
        workflow_conclusion: success
    - name:
      run: ls