name: Vulkan Versions Tests

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
on: [push]



jobs: 
  vulkans:
    
    strategy:
      fail-fast: false
      matrix:
        include:
        
          - vulkan-version: sdk-1.2.170
          - vulkan-version: v1.1.115
          # - vulkan-version: ubuntu-latest
          # - vulkan-version: ubuntu-latest
          # - vulkan-version: ubuntu-latest
          # - vulkan-version: ubuntu-latest
          # - vulkan-version: ubuntu-latest
          # - vulkan-version: ubuntu-latest
          # - vulkan-version: ubuntu-latest
          # - vulkan-version: ubuntu-latest


    name: Vulkan • ${{ matrix.vulkan-version }}
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Vulkan Kompute's Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y cmake
          sudo apt install -y g++
          sudo apt install -y python3
          sudo apt install -y libfmt-dev -y
          sudo apt install -y libspdlog-dev -y
          sudo apt install -y glslang-dev -y

      - name: Building custom Vulkan
        run: |
          VULKAN_VERSION=sdk-1.2.162
          mkdir VULKAN_SDK
          mkdir VULKAN_SDK/_build
          cd VULKAN_SDK/_build
          git clone https://github.com/KhronosGroup/Vulkan-Headers.git --branch $VULKAN_VERSION
          cd Vulkan-Headers
          cmake -DCMAKE_INSTALL_PREFIX=../.. -DCMAKE_BUILD_TYPE=Release . 
          cmake --build . --config Release
          cmake --install .
          cd ..
          git clone https://github.com/KhronosGroup/Vulkan-Loader.git --branch $VULKAN_VERSION
          cd Vulkan-Loader
          cmake -DVULKAN_HEADERS_INSTALL_DIR=../.. -DCMAKE_INSTALL_PREFIX=../.. -DCMAKE_BUILD_TYPE=Release   \
              . -DBUILD_WSI_WAYLAND_SUPPORT=OFF -DBUILD_WSI_XLIB_SUPPORT=OFF
          cmake --build . --config Release
          cmake --install .
          cd ../..
          rm -rf VULKAN_SDK/_build

        - name: Configuring Vulkan Kompute
          run: |
            cmake -Bbuild/                               \
                  -DCMAKE_BUILD_TYPE=Debug               \
                  -DKOMPUTE_OPT_ENABLE_SPDLOG=1

        - name: Building Vulkan Kompute
          run: |
            cd build && make -j 2